[tool.poetry]
name = "cntext"
version = "2.2.1"
description = "Chinese text analysis library, which can perform word frequency statistics, dictionary expansion, sentiment analysis, similarity, readability, co-occurrence analysis, social computing (attitude, prejudice, culture) on texts; Now support Ollama(LLM) analysis"
authors = ["DaDeng"]
license = "MIT"
readme = "README.md"

# 包含非 Python 文件
packages = [
    { include = "cntext" },
]


[tool.poetry.dependencies]
python = "^3.8"
ftfy = "^6.2.0"
jieba = "^0.42"
numpy = "^1.26.4"
scikit-learn = "^1.5.0"
matplotlib = "^3.6.0"
PyMuPDF = "^1.25.4"
aiolimiter = "1.2.1"
nest-asyncio = "^1.6.0"
pyecharts = "2.0.0"
gensim = "^4.2.0"
nltk = "^3.8"
pandas = "^2.2.0"
chardet = "^5.0.0"
h5py = "^3.9.0"
distinctiveness = "^0.14.6"
networkx = "^3.2"
tqdm = "^4.66.4"
scipy = "^1.12.0"
python-docx = "^1.1.2"
opencc-python-reimplemented = "^0.1.6"
ollama = "^0.2.1"
pydantic="^2.11.7"
instructor="^1.11.2"
openai = "^1.107.0"
PyYAML='^6.0.2'
contractions='^0.1.73'



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"




[options]
package_data = "data/*.yaml"
include_package_data = true
zip_safe = false